export const events_dummy = [
  {
    id: '1',
    title: 'Annual Tech Conference',
    status: 'upcoming',
    date: '2025-09-15T10:00:00',
    location: 'San Francisco, CA',
    type: 'conference',
    currentParticipants: 120,
    maxParticipants: 200,
  },
  {
    id: '2',
    title: 'Hackathon 2025',
    status: 'ongoing',
    date: '2025-08-27T09:00:00',
    location: 'New York, NY',
    type: 'hackathon',
    currentParticipants: 80,
    maxParticipants: 100,
  },
  {
    id: '3',
    title: 'AI & Machine Learning Workshop',
    status: 'upcoming',
    date: '2025-09-05T14:00:00',
    location: 'Online',
    type: 'workshop',
    currentParticipants: 45,
    maxParticipants: 50,
  },
  {
    id: '4',
    title: 'Startup Networking Night',
    status: 'upcoming',
    date: '2025-09-20T18:30:00',
    location: 'Austin, TX',
    type: 'networking',
    currentParticipants: 200,
    maxParticipants: 200,
  },
  {
    id: '5',
    title: 'Cybersecurity Seminar',
    status: 'ongoing',
    date: '2025-08-27T11:00:00',
    location: 'Boston, MA',
    type: 'seminar',
    currentParticipants: 65,
    maxParticipants: 100,
  },
];
